site_name: iDEC Resources Wiki

theme:
    name: material
    logo: img/idec-logo-white-bg.png
    favicon: img/idec-logo.png

    palette:
        primary: deep purple
        accent: deep purple

    features:
        - header.autohide
        - navigation.expand

nav:
    - Home: index.md
    - About: about.md

repo_url: https://github.com/tyhho/mkdocs-material-test

edit_uri: blob/main/docs/

copyright: Copyright &copy; 2021 iDEC | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826